### ISSUE TITLE
Add age-gender group dropdown to sidebar when biomarker selected

### ISSUE THREAD

**Issue by bgsandan** [micronutrientsupport/micronutrient-support-tool#416]
# **User story**

As a nutritionist, I want to explore biomarker data for different age-gender groups.

## Summary

* When biomarker data is selected, the "Age-gender group" dropdown should be enabled. 
* The groups would be different for each micronutrient. 
* Some groups might have sub-groups. e.g. Children -> SAC (school-age children) and PSC (pre-school children).  What would be the best way to present these sub-groups in a dropdown.

[Figma prototype](https://www.figma.com/proto/swhv1D7WScZwDE5KKYkkaE/BMGF-Maps?node-id=1767%3A2426&viewport=-4666%2C-4960%2C0.269345760345459&scaling=contain&page-id=0%3A1&hide-ui=1)

## Wireframe

![szoter_annotated_image (1)](https://user-images.githubusercontent.com/72566636/115057216-b06ea600-9edb-11eb-82b7-8b98b3021fc1.jpeg)

## Resources

<details>
<summary>Demo data until API/DB routes complete</summary>
<p>
<pre>
* All
* Adult women
* Adult men
* Children
</pre>
</p>
</details>

# **Child Issues**

## **Front-End**

*   N/A

## **API**

*   micronutrientsupport/api#97

## **Database**

*   micronutrientsupport/database-architecture#120

# **Related Issues**

#419 Data source drop down in the sidebar for biomarker data

# **Acceptance Criteria**

*   [x] Dropdown only appears if biomarker data is selected
*   [x] Dropdown content is populated from API
*   [x] Selected group is added to URL query string
*   [x] When biomarker page loaded the query string value is validated in the route guard
*   [x] When biomarker page loaded the query string value is retrieved and loaded into the quickmaps service

**Comment by Sveouu** [comment]
- [ ] Dropdown only appears if biomarker data is selected --> complete based on demo data

**Comment by jon571** [comment]
I've added a couple more acceptance criteria points associated with the query string.  If you want me to take over this task to do these query string interactions @Sveouu then I'm happy to do so :-)

**Comment by jon571** [comment]
@Sveouu I'm going to do the API changes for #419.  I can do api bits for this issue if you haven't already started looking at that?

**Comment by Sveouu** [comment]
@jon571  Hi, no I have not yet started looking at that (needed to attend a different project meeting) Happy for you to go ahead and catch-up on it tomorrow as you are probably needing to head off soon?

**Comment by jon571** [comment]
@bgsandan, on the sub-group question, it might be simpler to just have a flat list.  You could always have the same prefix e.g.
- Children - SAC (school-age children)
- Children - PSC (pre-school children)

**Comment by Sveouu** [comment]
@jon571 I agree with avoiding sub-groups if they are not really necessary. I had a look at using a nested menu selection, but could not get the example to work with the mat-form-field.

**Comment by bgsandan** [comment]
Sorry just seen this.  Yes, a flat list is absolutely fine

**Comment by Sveouu** [comment]
@jon571 thanks for setting up the API.
a few of the tasks above could be ticked of, however I could use some help tomorrow when looking at the route guard

**Comment by jon571** [comment]
@Sveouu that area is a bit complicated.  I tried to simplify it all a bit in the last sprint but can't remember exactly what is required off the top of my head.  
Do you want to push up your changes and tell me which branch you're working on?  I can then have a look, familiarise myself with it and work out what is needed. :-)

**Comment by Sveouu** [comment]
Hi @jon571  I pushed up to the branch  sr_416_group_drowpdown

**Comment by Sveouu** [comment]
@bgsandan   All above issues have been resolved thanks to @jon571 
There is a small query which would be good to demonstrate and get your opinion on.

**Comment by jon571** [comment]
@bgsandan 
The query that Svea refers to is that due to the age-gender only being applicable to the biomarker page, if you have a selection that allows biomarker and diet the following occurs:

Start here: 

With biomarker selected:
- clicking "view results" takes you to the biomarker page.
- clicking "diet" takes you to the diet page
- clicking biomarker again takes you to the biomarker page

All is good.

With diet selected (page should be reloaded so that hidden age-gender select is now empty):
- clicking "view results" takes you to the diet page.
- clicking "biomarker" takes you to the **location select** page.  The route guard acted since no age-gender selection made.  The incorrect parameters dialog also shows as this is triggered in the route guard.

We know this last bit is wrong, but the question is what would be correct?

**Comment by jon571** [comment]
Could we default the selection to the "all" item (or preferably the first item)?  This would certainly solve this issue but would it be appropriate?

**Comment by bgsandan** [comment]
Hi @jon571 @Sveouu .  Thanks for this.  Sorry for the delay in response to the issue.  Yes I see the problem with the age-gender selection not having a selected or default value. 

I think having a default value will be fine.  Our user testing last week showed Women of Reproductive age (WRA) as being the highest priority group so we will probably go for that.  However from a front-end perspective I think defaulting to the first item in the list is fine.  We can then handle the ordering in the API response that feeds the dropdown (when it exists).

Does that work for you?

**Comment by jon571** [comment]
So the functionality that is in PR #443 is:
- if a user tries to go directly to the biomarker page (from a linked url) the age-gender is required and validated.
- if a user tries to navigate within the app, from the diet pages to the biomarker page, the age-gender value defaults to the first item retrieved.
- Within the quickmaps sidebar, when the age-gender options are updated (due to a dependant option being changed) an attempt is made to reselect the previously selected option (same id), and if this is not available (or there wasn't a previous selection) the first option is selected.

Hi @bgsandan.
Please review the functionality in PR #443, refering to the comments on this task, when you have a chance :-)

**Comment by jon571** [comment]
Re-assigned PR as @bgsandan not in today.

**Comment by bgsandan** [comment]
Looks good to me.  Closing :+1:
